spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: customer
              uri: lb://CUSTOMER
              predicates:
                - Path=/customer/**
            - id: order
              uri: lb://ORDER
              predicates:
                - Path=/api/v1/orders/**
            - id: product
              uri: lb://PRODUCT
              predicates:
                - Path=/api/v1/products/**
            - id: payment
              uri: lb://PAYMENT
              predicates:
                - Path=/api/v1/payments/**

  datasource:
    url: jdbc:mysql://localhost:3306/gateway_db?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8222
management:
  tracing:
    sampling:
      probability: 1.0